aws_dbt_snow_project:
  outputs:
    dev:
      account: 
      database: 
      password: 
      role: 
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: 
      warehouse: COMPUTE_WH
  target: dev

