aws_dbt_snow_project:
  outputs:
    dev:
      account: JHVVMYB-FWB12512
      database: AIRBNB
      password: Ph!lt0r1nf0M@t1cs
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: mahin1211
      warehouse: COMPUTE_WH
  target: dev

